volumes:
  db-data:


services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: tail -f /dev/null
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "1323:1323"
    volumes:
      - .:/app
    command: tail -f /dev/null
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_database
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
