FROM golang:1.21
ENV TZ=Asia/Tokyo LANG=C.UTF-8
WORKDIR /app

# Install system dependencies first
# https://stripe.com/docs/stripe-cli#install
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -s https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | gpg --dearmor | tee /usr/share/keyrings/stripe.gpg && \
  echo "deb [signed-by=/usr/share/keyrings/stripe.gpg] https://packages.stripe.dev/stripe-cli-debian-local stable main" | tee -a /etc/apt/sources.list.d/stripe.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends postgresql-client stripe expect && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Install Golang extensions and tools
# for golang extension
RUN go install github.com/ramya-rao-a/go-outline@latest && \
  go install golang.org/x/tools/gopls@latest && \
  go install golang.org/x/tools/cmd/goimports@latest && \
  go install honnef.co/go/tools/cmd/staticcheck@latest && \
  go install github.com/cosmtrek/air@latest && \
  go install github.com/go-delve/delve/cmd/dlv@latest && \
  go install github.com/volatiletech/sqlboiler/v4@latest && \
  go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest

# Install migrate tool
RUN mkdir golang-migrate-tmp-dir && \
  curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz -C golang-migrate-tmp-dir && \
  mv golang-migrate-tmp-dir/migrate /usr/local/bin/migrate && \
  rm -rf golang-migrate-tmp-dir
