// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	PaymentStripe    string
	SchemaMigrations string
}{
	PaymentStripe:    "payment_stripe",
	SchemaMigrations: "schema_migrations",
}
