// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Customers        string
	SchemaMigrations string
	StripeOrderItems string
	StripePrices     string
	StripeProducts   string
	StripeRecurrings string
}{
	Customers:        "customers",
	SchemaMigrations: "schema_migrations",
	StripeOrderItems: "stripe_order_items",
	StripePrices:     "stripe_prices",
	StripeProducts:   "stripe_products",
	StripeRecurrings: "stripe_recurrings",
}
