// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPaymentStripes(t *testing.T) {
	t.Parallel()

	query := PaymentStripes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPaymentStripesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPaymentStripesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := PaymentStripes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPaymentStripesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PaymentStripeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPaymentStripesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PaymentStripeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if PaymentStripe exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PaymentStripeExists to return true, but got false.")
	}
}

func testPaymentStripesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	paymentStripeFound, err := FindPaymentStripe(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if paymentStripeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPaymentStripesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = PaymentStripes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPaymentStripesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := PaymentStripes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPaymentStripesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	paymentStripeOne := &PaymentStripe{}
	paymentStripeTwo := &PaymentStripe{}
	if err = randomize.Struct(seed, paymentStripeOne, paymentStripeDBTypes, false, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}
	if err = randomize.Struct(seed, paymentStripeTwo, paymentStripeDBTypes, false, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = paymentStripeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = paymentStripeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PaymentStripes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPaymentStripesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	paymentStripeOne := &PaymentStripe{}
	paymentStripeTwo := &PaymentStripe{}
	if err = randomize.Struct(seed, paymentStripeOne, paymentStripeDBTypes, false, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}
	if err = randomize.Struct(seed, paymentStripeTwo, paymentStripeDBTypes, false, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = paymentStripeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = paymentStripeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func paymentStripeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func paymentStripeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func paymentStripeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func paymentStripeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func paymentStripeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func paymentStripeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func paymentStripeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func paymentStripeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func paymentStripeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PaymentStripe) error {
	*o = PaymentStripe{}
	return nil
}

func testPaymentStripesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &PaymentStripe{}
	o := &PaymentStripe{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize PaymentStripe object: %s", err)
	}

	AddPaymentStripeHook(boil.BeforeInsertHook, paymentStripeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	paymentStripeBeforeInsertHooks = []PaymentStripeHook{}

	AddPaymentStripeHook(boil.AfterInsertHook, paymentStripeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	paymentStripeAfterInsertHooks = []PaymentStripeHook{}

	AddPaymentStripeHook(boil.AfterSelectHook, paymentStripeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	paymentStripeAfterSelectHooks = []PaymentStripeHook{}

	AddPaymentStripeHook(boil.BeforeUpdateHook, paymentStripeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	paymentStripeBeforeUpdateHooks = []PaymentStripeHook{}

	AddPaymentStripeHook(boil.AfterUpdateHook, paymentStripeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	paymentStripeAfterUpdateHooks = []PaymentStripeHook{}

	AddPaymentStripeHook(boil.BeforeDeleteHook, paymentStripeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	paymentStripeBeforeDeleteHooks = []PaymentStripeHook{}

	AddPaymentStripeHook(boil.AfterDeleteHook, paymentStripeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	paymentStripeAfterDeleteHooks = []PaymentStripeHook{}

	AddPaymentStripeHook(boil.BeforeUpsertHook, paymentStripeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	paymentStripeBeforeUpsertHooks = []PaymentStripeHook{}

	AddPaymentStripeHook(boil.AfterUpsertHook, paymentStripeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	paymentStripeAfterUpsertHooks = []PaymentStripeHook{}
}

func testPaymentStripesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPaymentStripesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(paymentStripeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPaymentStripesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPaymentStripesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PaymentStripeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPaymentStripesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PaymentStripes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	paymentStripeDBTypes = map[string]string{`ID`: `bigint`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `Link`: `character varying`}
	_                    = bytes.MinRead
)

func testPaymentStripesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(paymentStripePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(paymentStripeAllColumns) == len(paymentStripePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPaymentStripesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(paymentStripeAllColumns) == len(paymentStripePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PaymentStripe{}
	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, paymentStripeDBTypes, true, paymentStripePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(paymentStripeAllColumns, paymentStripePrimaryKeyColumns) {
		fields = paymentStripeAllColumns
	} else {
		fields = strmangle.SetComplement(
			paymentStripeAllColumns,
			paymentStripePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PaymentStripeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPaymentStripesUpsert(t *testing.T) {
	t.Parallel()

	if len(paymentStripeAllColumns) == len(paymentStripePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := PaymentStripe{}
	if err = randomize.Struct(seed, &o, paymentStripeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PaymentStripe: %s", err)
	}

	count, err := PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, paymentStripeDBTypes, false, paymentStripePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PaymentStripe struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PaymentStripe: %s", err)
	}

	count, err = PaymentStripes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
