// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// StripeOrderItem is an object representing the database table.
type StripeOrderItem struct {
	ID            int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt     time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	StripePriceID int64     `boil:"stripe_price_id" json:"stripe_price_id" toml:"stripe_price_id" yaml:"stripe_price_id"`

	R *stripeOrderItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L stripeOrderItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var StripeOrderItemColumns = struct {
	ID            string
	CreatedAt     string
	UpdatedAt     string
	StripePriceID string
}{
	ID:            "id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	StripePriceID: "stripe_price_id",
}

var StripeOrderItemTableColumns = struct {
	ID            string
	CreatedAt     string
	UpdatedAt     string
	StripePriceID string
}{
	ID:            "stripe_order_items.id",
	CreatedAt:     "stripe_order_items.created_at",
	UpdatedAt:     "stripe_order_items.updated_at",
	StripePriceID: "stripe_order_items.stripe_price_id",
}

// Generated where

var StripeOrderItemWhere = struct {
	ID            whereHelperint64
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
	StripePriceID whereHelperint64
}{
	ID:            whereHelperint64{field: "\"stripe_order_items\".\"id\""},
	CreatedAt:     whereHelpertime_Time{field: "\"stripe_order_items\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"stripe_order_items\".\"updated_at\""},
	StripePriceID: whereHelperint64{field: "\"stripe_order_items\".\"stripe_price_id\""},
}

// StripeOrderItemRels is where relationship names are stored.
var StripeOrderItemRels = struct {
}{}

// stripeOrderItemR is where relationships are stored.
type stripeOrderItemR struct {
}

// NewStruct creates a new relationship struct
func (*stripeOrderItemR) NewStruct() *stripeOrderItemR {
	return &stripeOrderItemR{}
}

// stripeOrderItemL is where Load methods for each relationship are stored.
type stripeOrderItemL struct{}

var (
	stripeOrderItemAllColumns            = []string{"id", "created_at", "updated_at", "stripe_price_id"}
	stripeOrderItemColumnsWithoutDefault = []string{"created_at", "updated_at", "stripe_price_id"}
	stripeOrderItemColumnsWithDefault    = []string{"id"}
	stripeOrderItemPrimaryKeyColumns     = []string{"id"}
	stripeOrderItemGeneratedColumns      = []string{}
)

type (
	// StripeOrderItemSlice is an alias for a slice of pointers to StripeOrderItem.
	// This should almost always be used instead of []StripeOrderItem.
	StripeOrderItemSlice []*StripeOrderItem
	// StripeOrderItemHook is the signature for custom StripeOrderItem hook methods
	StripeOrderItemHook func(context.Context, boil.ContextExecutor, *StripeOrderItem) error

	stripeOrderItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	stripeOrderItemType                 = reflect.TypeOf(&StripeOrderItem{})
	stripeOrderItemMapping              = queries.MakeStructMapping(stripeOrderItemType)
	stripeOrderItemPrimaryKeyMapping, _ = queries.BindMapping(stripeOrderItemType, stripeOrderItemMapping, stripeOrderItemPrimaryKeyColumns)
	stripeOrderItemInsertCacheMut       sync.RWMutex
	stripeOrderItemInsertCache          = make(map[string]insertCache)
	stripeOrderItemUpdateCacheMut       sync.RWMutex
	stripeOrderItemUpdateCache          = make(map[string]updateCache)
	stripeOrderItemUpsertCacheMut       sync.RWMutex
	stripeOrderItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var stripeOrderItemAfterSelectHooks []StripeOrderItemHook

var stripeOrderItemBeforeInsertHooks []StripeOrderItemHook
var stripeOrderItemAfterInsertHooks []StripeOrderItemHook

var stripeOrderItemBeforeUpdateHooks []StripeOrderItemHook
var stripeOrderItemAfterUpdateHooks []StripeOrderItemHook

var stripeOrderItemBeforeDeleteHooks []StripeOrderItemHook
var stripeOrderItemAfterDeleteHooks []StripeOrderItemHook

var stripeOrderItemBeforeUpsertHooks []StripeOrderItemHook
var stripeOrderItemAfterUpsertHooks []StripeOrderItemHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *StripeOrderItem) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *StripeOrderItem) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *StripeOrderItem) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *StripeOrderItem) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *StripeOrderItem) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *StripeOrderItem) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *StripeOrderItem) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *StripeOrderItem) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *StripeOrderItem) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stripeOrderItemAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddStripeOrderItemHook registers your hook function for all future operations.
func AddStripeOrderItemHook(hookPoint boil.HookPoint, stripeOrderItemHook StripeOrderItemHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		stripeOrderItemAfterSelectHooks = append(stripeOrderItemAfterSelectHooks, stripeOrderItemHook)
	case boil.BeforeInsertHook:
		stripeOrderItemBeforeInsertHooks = append(stripeOrderItemBeforeInsertHooks, stripeOrderItemHook)
	case boil.AfterInsertHook:
		stripeOrderItemAfterInsertHooks = append(stripeOrderItemAfterInsertHooks, stripeOrderItemHook)
	case boil.BeforeUpdateHook:
		stripeOrderItemBeforeUpdateHooks = append(stripeOrderItemBeforeUpdateHooks, stripeOrderItemHook)
	case boil.AfterUpdateHook:
		stripeOrderItemAfterUpdateHooks = append(stripeOrderItemAfterUpdateHooks, stripeOrderItemHook)
	case boil.BeforeDeleteHook:
		stripeOrderItemBeforeDeleteHooks = append(stripeOrderItemBeforeDeleteHooks, stripeOrderItemHook)
	case boil.AfterDeleteHook:
		stripeOrderItemAfterDeleteHooks = append(stripeOrderItemAfterDeleteHooks, stripeOrderItemHook)
	case boil.BeforeUpsertHook:
		stripeOrderItemBeforeUpsertHooks = append(stripeOrderItemBeforeUpsertHooks, stripeOrderItemHook)
	case boil.AfterUpsertHook:
		stripeOrderItemAfterUpsertHooks = append(stripeOrderItemAfterUpsertHooks, stripeOrderItemHook)
	}
}

// One returns a single stripeOrderItem record from the query.
func (q stripeOrderItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*StripeOrderItem, error) {
	o := &StripeOrderItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for stripe_order_items")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all StripeOrderItem records from the query.
func (q stripeOrderItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (StripeOrderItemSlice, error) {
	var o []*StripeOrderItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to StripeOrderItem slice")
	}

	if len(stripeOrderItemAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all StripeOrderItem records in the query.
func (q stripeOrderItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count stripe_order_items rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q stripeOrderItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if stripe_order_items exists")
	}

	return count > 0, nil
}

// StripeOrderItems retrieves all the records using an executor.
func StripeOrderItems(mods ...qm.QueryMod) stripeOrderItemQuery {
	mods = append(mods, qm.From("\"stripe_order_items\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"stripe_order_items\".*"})
	}

	return stripeOrderItemQuery{q}
}

// FindStripeOrderItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindStripeOrderItem(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*StripeOrderItem, error) {
	stripeOrderItemObj := &StripeOrderItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"stripe_order_items\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, stripeOrderItemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from stripe_order_items")
	}

	if err = stripeOrderItemObj.doAfterSelectHooks(ctx, exec); err != nil {
		return stripeOrderItemObj, err
	}

	return stripeOrderItemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *StripeOrderItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no stripe_order_items provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(stripeOrderItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	stripeOrderItemInsertCacheMut.RLock()
	cache, cached := stripeOrderItemInsertCache[key]
	stripeOrderItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			stripeOrderItemAllColumns,
			stripeOrderItemColumnsWithDefault,
			stripeOrderItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(stripeOrderItemType, stripeOrderItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(stripeOrderItemType, stripeOrderItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"stripe_order_items\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"stripe_order_items\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into stripe_order_items")
	}

	if !cached {
		stripeOrderItemInsertCacheMut.Lock()
		stripeOrderItemInsertCache[key] = cache
		stripeOrderItemInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the StripeOrderItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *StripeOrderItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	stripeOrderItemUpdateCacheMut.RLock()
	cache, cached := stripeOrderItemUpdateCache[key]
	stripeOrderItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			stripeOrderItemAllColumns,
			stripeOrderItemPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update stripe_order_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"stripe_order_items\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, stripeOrderItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(stripeOrderItemType, stripeOrderItemMapping, append(wl, stripeOrderItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update stripe_order_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for stripe_order_items")
	}

	if !cached {
		stripeOrderItemUpdateCacheMut.Lock()
		stripeOrderItemUpdateCache[key] = cache
		stripeOrderItemUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q stripeOrderItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for stripe_order_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for stripe_order_items")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o StripeOrderItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stripeOrderItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"stripe_order_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, stripeOrderItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in stripeOrderItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all stripeOrderItem")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *StripeOrderItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no stripe_order_items provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(stripeOrderItemColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	stripeOrderItemUpsertCacheMut.RLock()
	cache, cached := stripeOrderItemUpsertCache[key]
	stripeOrderItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			stripeOrderItemAllColumns,
			stripeOrderItemColumnsWithDefault,
			stripeOrderItemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			stripeOrderItemAllColumns,
			stripeOrderItemPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert stripe_order_items, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(stripeOrderItemPrimaryKeyColumns))
			copy(conflict, stripeOrderItemPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"stripe_order_items\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(stripeOrderItemType, stripeOrderItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(stripeOrderItemType, stripeOrderItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert stripe_order_items")
	}

	if !cached {
		stripeOrderItemUpsertCacheMut.Lock()
		stripeOrderItemUpsertCache[key] = cache
		stripeOrderItemUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single StripeOrderItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *StripeOrderItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no StripeOrderItem provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), stripeOrderItemPrimaryKeyMapping)
	sql := "DELETE FROM \"stripe_order_items\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from stripe_order_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for stripe_order_items")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q stripeOrderItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no stripeOrderItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from stripe_order_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for stripe_order_items")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o StripeOrderItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(stripeOrderItemBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stripeOrderItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"stripe_order_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, stripeOrderItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from stripeOrderItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for stripe_order_items")
	}

	if len(stripeOrderItemAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *StripeOrderItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindStripeOrderItem(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StripeOrderItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := StripeOrderItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stripeOrderItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"stripe_order_items\".* FROM \"stripe_order_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, stripeOrderItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in StripeOrderItemSlice")
	}

	*o = slice

	return nil
}

// StripeOrderItemExists checks if the StripeOrderItem row exists.
func StripeOrderItemExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"stripe_order_items\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if stripe_order_items exists")
	}

	return exists, nil
}

// Exists checks if the StripeOrderItem row exists.
func (o *StripeOrderItem) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return StripeOrderItemExists(ctx, exec, o.ID)
}
