// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStripeRecurrings(t *testing.T) {
	t.Parallel()

	query := StripeRecurrings()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStripeRecurringsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeRecurringsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := StripeRecurrings().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeRecurringsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StripeRecurringSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeRecurringsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StripeRecurringExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if StripeRecurring exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StripeRecurringExists to return true, but got false.")
	}
}

func testStripeRecurringsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	stripeRecurringFound, err := FindStripeRecurring(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if stripeRecurringFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStripeRecurringsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = StripeRecurrings().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStripeRecurringsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := StripeRecurrings().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStripeRecurringsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	stripeRecurringOne := &StripeRecurring{}
	stripeRecurringTwo := &StripeRecurring{}
	if err = randomize.Struct(seed, stripeRecurringOne, stripeRecurringDBTypes, false, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}
	if err = randomize.Struct(seed, stripeRecurringTwo, stripeRecurringDBTypes, false, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stripeRecurringOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stripeRecurringTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StripeRecurrings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStripeRecurringsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	stripeRecurringOne := &StripeRecurring{}
	stripeRecurringTwo := &StripeRecurring{}
	if err = randomize.Struct(seed, stripeRecurringOne, stripeRecurringDBTypes, false, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}
	if err = randomize.Struct(seed, stripeRecurringTwo, stripeRecurringDBTypes, false, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stripeRecurringOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stripeRecurringTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func stripeRecurringBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func stripeRecurringAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func stripeRecurringAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func stripeRecurringBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func stripeRecurringAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func stripeRecurringBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func stripeRecurringAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func stripeRecurringBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func stripeRecurringAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeRecurring) error {
	*o = StripeRecurring{}
	return nil
}

func testStripeRecurringsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &StripeRecurring{}
	o := &StripeRecurring{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, false); err != nil {
		t.Errorf("Unable to randomize StripeRecurring object: %s", err)
	}

	AddStripeRecurringHook(boil.BeforeInsertHook, stripeRecurringBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	stripeRecurringBeforeInsertHooks = []StripeRecurringHook{}

	AddStripeRecurringHook(boil.AfterInsertHook, stripeRecurringAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	stripeRecurringAfterInsertHooks = []StripeRecurringHook{}

	AddStripeRecurringHook(boil.AfterSelectHook, stripeRecurringAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	stripeRecurringAfterSelectHooks = []StripeRecurringHook{}

	AddStripeRecurringHook(boil.BeforeUpdateHook, stripeRecurringBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	stripeRecurringBeforeUpdateHooks = []StripeRecurringHook{}

	AddStripeRecurringHook(boil.AfterUpdateHook, stripeRecurringAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	stripeRecurringAfterUpdateHooks = []StripeRecurringHook{}

	AddStripeRecurringHook(boil.BeforeDeleteHook, stripeRecurringBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	stripeRecurringBeforeDeleteHooks = []StripeRecurringHook{}

	AddStripeRecurringHook(boil.AfterDeleteHook, stripeRecurringAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	stripeRecurringAfterDeleteHooks = []StripeRecurringHook{}

	AddStripeRecurringHook(boil.BeforeUpsertHook, stripeRecurringBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	stripeRecurringBeforeUpsertHooks = []StripeRecurringHook{}

	AddStripeRecurringHook(boil.AfterUpsertHook, stripeRecurringAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	stripeRecurringAfterUpsertHooks = []StripeRecurringHook{}
}

func testStripeRecurringsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStripeRecurringsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(stripeRecurringColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStripeRecurringsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStripeRecurringsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StripeRecurringSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStripeRecurringsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StripeRecurrings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	stripeRecurringDBTypes = map[string]string{`ID`: `bigint`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`, `Interval`: `text`, `IntervalCount`: `smallint`, `StripePriceID`: `bigint`}
	_                      = bytes.MinRead
)

func testStripeRecurringsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(stripeRecurringPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(stripeRecurringAllColumns) == len(stripeRecurringPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStripeRecurringsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(stripeRecurringAllColumns) == len(stripeRecurringPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StripeRecurring{}
	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stripeRecurringDBTypes, true, stripeRecurringPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(stripeRecurringAllColumns, stripeRecurringPrimaryKeyColumns) {
		fields = stripeRecurringAllColumns
	} else {
		fields = strmangle.SetComplement(
			stripeRecurringAllColumns,
			stripeRecurringPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StripeRecurringSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStripeRecurringsUpsert(t *testing.T) {
	t.Parallel()

	if len(stripeRecurringAllColumns) == len(stripeRecurringPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := StripeRecurring{}
	if err = randomize.Struct(seed, &o, stripeRecurringDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StripeRecurring: %s", err)
	}

	count, err := StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, stripeRecurringDBTypes, false, stripeRecurringPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeRecurring struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StripeRecurring: %s", err)
	}

	count, err = StripeRecurrings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
