// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStripeProducts(t *testing.T) {
	t.Parallel()

	query := StripeProducts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStripeProductsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeProductsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := StripeProducts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeProductsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StripeProductSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeProductsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StripeProductExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if StripeProduct exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StripeProductExists to return true, but got false.")
	}
}

func testStripeProductsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	stripeProductFound, err := FindStripeProduct(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if stripeProductFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStripeProductsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = StripeProducts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStripeProductsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := StripeProducts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStripeProductsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	stripeProductOne := &StripeProduct{}
	stripeProductTwo := &StripeProduct{}
	if err = randomize.Struct(seed, stripeProductOne, stripeProductDBTypes, false, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}
	if err = randomize.Struct(seed, stripeProductTwo, stripeProductDBTypes, false, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stripeProductOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stripeProductTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StripeProducts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStripeProductsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	stripeProductOne := &StripeProduct{}
	stripeProductTwo := &StripeProduct{}
	if err = randomize.Struct(seed, stripeProductOne, stripeProductDBTypes, false, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}
	if err = randomize.Struct(seed, stripeProductTwo, stripeProductDBTypes, false, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stripeProductOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stripeProductTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func stripeProductBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func stripeProductAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func stripeProductAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func stripeProductBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func stripeProductAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func stripeProductBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func stripeProductAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func stripeProductBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func stripeProductAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeProduct) error {
	*o = StripeProduct{}
	return nil
}

func testStripeProductsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &StripeProduct{}
	o := &StripeProduct{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, stripeProductDBTypes, false); err != nil {
		t.Errorf("Unable to randomize StripeProduct object: %s", err)
	}

	AddStripeProductHook(boil.BeforeInsertHook, stripeProductBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	stripeProductBeforeInsertHooks = []StripeProductHook{}

	AddStripeProductHook(boil.AfterInsertHook, stripeProductAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	stripeProductAfterInsertHooks = []StripeProductHook{}

	AddStripeProductHook(boil.AfterSelectHook, stripeProductAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	stripeProductAfterSelectHooks = []StripeProductHook{}

	AddStripeProductHook(boil.BeforeUpdateHook, stripeProductBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	stripeProductBeforeUpdateHooks = []StripeProductHook{}

	AddStripeProductHook(boil.AfterUpdateHook, stripeProductAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	stripeProductAfterUpdateHooks = []StripeProductHook{}

	AddStripeProductHook(boil.BeforeDeleteHook, stripeProductBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	stripeProductBeforeDeleteHooks = []StripeProductHook{}

	AddStripeProductHook(boil.AfterDeleteHook, stripeProductAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	stripeProductAfterDeleteHooks = []StripeProductHook{}

	AddStripeProductHook(boil.BeforeUpsertHook, stripeProductBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	stripeProductBeforeUpsertHooks = []StripeProductHook{}

	AddStripeProductHook(boil.AfterUpsertHook, stripeProductAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	stripeProductAfterUpsertHooks = []StripeProductHook{}
}

func testStripeProductsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStripeProductsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(stripeProductColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStripeProductsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStripeProductsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StripeProductSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStripeProductsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StripeProducts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	stripeProductDBTypes = map[string]string{`ID`: `bigint`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`, `Name`: `text`, `IDOnStripe`: `text`}
	_                    = bytes.MinRead
)

func testStripeProductsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(stripeProductPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(stripeProductAllColumns) == len(stripeProductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStripeProductsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(stripeProductAllColumns) == len(stripeProductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StripeProduct{}
	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stripeProductDBTypes, true, stripeProductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(stripeProductAllColumns, stripeProductPrimaryKeyColumns) {
		fields = stripeProductAllColumns
	} else {
		fields = strmangle.SetComplement(
			stripeProductAllColumns,
			stripeProductPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StripeProductSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStripeProductsUpsert(t *testing.T) {
	t.Parallel()

	if len(stripeProductAllColumns) == len(stripeProductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := StripeProduct{}
	if err = randomize.Struct(seed, &o, stripeProductDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StripeProduct: %s", err)
	}

	count, err := StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, stripeProductDBTypes, false, stripeProductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeProduct struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StripeProduct: %s", err)
	}

	count, err = StripeProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
