// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStripeOrderItems(t *testing.T) {
	t.Parallel()

	query := StripeOrderItems()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStripeOrderItemsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeOrderItemsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := StripeOrderItems().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeOrderItemsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StripeOrderItemSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStripeOrderItemsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StripeOrderItemExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if StripeOrderItem exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StripeOrderItemExists to return true, but got false.")
	}
}

func testStripeOrderItemsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	stripeOrderItemFound, err := FindStripeOrderItem(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if stripeOrderItemFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStripeOrderItemsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = StripeOrderItems().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStripeOrderItemsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := StripeOrderItems().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStripeOrderItemsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	stripeOrderItemOne := &StripeOrderItem{}
	stripeOrderItemTwo := &StripeOrderItem{}
	if err = randomize.Struct(seed, stripeOrderItemOne, stripeOrderItemDBTypes, false, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}
	if err = randomize.Struct(seed, stripeOrderItemTwo, stripeOrderItemDBTypes, false, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stripeOrderItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stripeOrderItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StripeOrderItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStripeOrderItemsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	stripeOrderItemOne := &StripeOrderItem{}
	stripeOrderItemTwo := &StripeOrderItem{}
	if err = randomize.Struct(seed, stripeOrderItemOne, stripeOrderItemDBTypes, false, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}
	if err = randomize.Struct(seed, stripeOrderItemTwo, stripeOrderItemDBTypes, false, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stripeOrderItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stripeOrderItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func stripeOrderItemBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func stripeOrderItemAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func stripeOrderItemAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func stripeOrderItemBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func stripeOrderItemAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func stripeOrderItemBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func stripeOrderItemAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func stripeOrderItemBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func stripeOrderItemAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StripeOrderItem) error {
	*o = StripeOrderItem{}
	return nil
}

func testStripeOrderItemsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &StripeOrderItem{}
	o := &StripeOrderItem{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, false); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem object: %s", err)
	}

	AddStripeOrderItemHook(boil.BeforeInsertHook, stripeOrderItemBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemBeforeInsertHooks = []StripeOrderItemHook{}

	AddStripeOrderItemHook(boil.AfterInsertHook, stripeOrderItemAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemAfterInsertHooks = []StripeOrderItemHook{}

	AddStripeOrderItemHook(boil.AfterSelectHook, stripeOrderItemAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemAfterSelectHooks = []StripeOrderItemHook{}

	AddStripeOrderItemHook(boil.BeforeUpdateHook, stripeOrderItemBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemBeforeUpdateHooks = []StripeOrderItemHook{}

	AddStripeOrderItemHook(boil.AfterUpdateHook, stripeOrderItemAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemAfterUpdateHooks = []StripeOrderItemHook{}

	AddStripeOrderItemHook(boil.BeforeDeleteHook, stripeOrderItemBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemBeforeDeleteHooks = []StripeOrderItemHook{}

	AddStripeOrderItemHook(boil.AfterDeleteHook, stripeOrderItemAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemAfterDeleteHooks = []StripeOrderItemHook{}

	AddStripeOrderItemHook(boil.BeforeUpsertHook, stripeOrderItemBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemBeforeUpsertHooks = []StripeOrderItemHook{}

	AddStripeOrderItemHook(boil.AfterUpsertHook, stripeOrderItemAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	stripeOrderItemAfterUpsertHooks = []StripeOrderItemHook{}
}

func testStripeOrderItemsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStripeOrderItemsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(stripeOrderItemColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStripeOrderItemsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStripeOrderItemsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StripeOrderItemSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStripeOrderItemsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StripeOrderItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	stripeOrderItemDBTypes = map[string]string{`ID`: `bigint`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`, `StripePriceID`: `bigint`}
	_                      = bytes.MinRead
)

func testStripeOrderItemsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(stripeOrderItemPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(stripeOrderItemAllColumns) == len(stripeOrderItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStripeOrderItemsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(stripeOrderItemAllColumns) == len(stripeOrderItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StripeOrderItem{}
	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stripeOrderItemDBTypes, true, stripeOrderItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(stripeOrderItemAllColumns, stripeOrderItemPrimaryKeyColumns) {
		fields = stripeOrderItemAllColumns
	} else {
		fields = strmangle.SetComplement(
			stripeOrderItemAllColumns,
			stripeOrderItemPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StripeOrderItemSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStripeOrderItemsUpsert(t *testing.T) {
	t.Parallel()

	if len(stripeOrderItemAllColumns) == len(stripeOrderItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := StripeOrderItem{}
	if err = randomize.Struct(seed, &o, stripeOrderItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StripeOrderItem: %s", err)
	}

	count, err := StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, stripeOrderItemDBTypes, false, stripeOrderItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StripeOrderItem struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StripeOrderItem: %s", err)
	}

	count, err = StripeOrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
